<?php
$title = 'Freunde';
$this->placeholder('pageTitle')->set($title);
?>
<div class="row">
    <div class="col-md-3">
        <?php $partial = array('to-you-do/navigation/main.phtml', 'default') ?>
        <?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
        <?php echo $this->navigation('navigation')->menu()->render() ?>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-warning">
                    <div class="panel-heading">Suche</div>
                    <div class="panel-body">
                        <?php if (isset($this->form)) : ?>
                            <?php $form = $this->form; ?>
                            <?php $form->setAttribute('class', 'form-horizontal'); ?>
                            <?php $form->setAttribute('id', 'form-search'); ?>
                            <?php $form->prepare(); ?>
                            <?= $this->form()->openTag($form) ?>
                        <div class="form-group">
                            <div class="col-md-12">
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <?= $this->formLabel($form->get('search')) ?>
                                        <?= $this->formElement($form->get('search')) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <?= $this->formElement($form->get('submit')) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <?= $this->form()->closeTag() ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php if (isset($result) && $result instanceof Zend\Db\ResultSet\ResultSet) : ?>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-warning">
                    <div class="panel-heading">Ergebnis</div>
                    <div class="panel-body">
                        <?php if ($result->count() > 0) : ?>
                        <div class="table">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Nickname</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($result as $user) : ?>
                                    <tr>
                                        <td><?= $user->getUsername() ?></td>
                                        <td><a href="<?= $this->url('friend', array('action' => 'request-friendship', 'id' => $user->getUser_id())) ?>">einladen</a></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                            <?php else : ?>
                        <p>Ihre Suche lieferte keine Treffer!</P>
                            <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>