<?php
$title = 'Listen';
$this->placeholder('pageTitle')->set($title);
?>
<div class="row">
    <div class="col-md-3">
        <?php $partial = array('to-you-do/navigation/main.phtml', 'default') ?>
        <?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
        <?php echo $this->navigation('navigation')->menu()->render() ?>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp;ToYouDo - <?= $list->getName() ?>
                        <a class="pull-right" href="<?= $this->url('list') ?>"><span class="glyphicon glyphicon-arrow-left">&nbsp;Zurück</span></a>
                    </div>
                    <div class="panel-body">
                        <p>
                            Erstellt für: 
                            <?= $list->getFriendName() ?>
                            <?= $list->getUserName() ?>
                        </p>
                        <p>
                            Deadline: 
                            <?= date('d.m.Y', strtotime($list->getDeadline())); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        Aufgaben
                        <a class="pull-right" href="<?= $this->url('list', array('action' => 'add-item', 'id' => $list->getId())) ?>"><span class="glyphicon glyphicon-plus"></span></a>
                    </div>
                    <div class="panel-body">
                        <?php if ($items->count() > 0) : ?>
                        <div class="table">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Bezeichnung</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($items as $item) : ?>
                                    <tr>
                                        <td><?= $item->getContent() ?></td>
                                        <td>
                                            <a class="pull-right" href="<?= $this->url('list', array('action' => 'delete-item', 'id' => $item->getId())) ?>"><span class="glyphicon glyphicon-remove">&nbsp;</span></a>
                                            <a class="pull-right" href="<?= $this->url('list', array('action' => 'edit-item', 'id' => $item->getId())) ?>"><span class="glyphicon glyphicon-pencil">&nbsp;</span></a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <?php else : ?>
                        Zur Zeit sind keine Aufgaben aufgelistet.
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>