<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Multi Page '. $this->translate('To You Do'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12 header">
                    <?php if ($this->zfcUserIdentity()) : ?>
                    <p class="pull-left login-row">Sie sind angemeldet als: <span class="highlight-user"><?= $this->zfcUserIdentity()->getUsername() ?></span>&nbsp;</p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row header-list">
                <div class="col-md-12 header-list">
                    <img class="pull-right" src="/img/head_list.png" alt="header"/>
                    <div class="page-title">
                        <h1><?= $this->placeholder('pageTitle') ?></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-warning panel-transparent">
                        <div class="panel-body">
                            <?php echo $this->content; ?>
                            <?php
                                $flash = $this->flashMessenger();
                                echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                            ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php if ($this->zfcUserIdentity()) : ?>
            <p class="pull-right">
                <a href="<?= $this->url('zfcuser/logout') ?>"><span class="glyphicon glyphicon-log-out">&nbsp;Abmelden</span></a>
            </p>
            <?php endif; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
